version: "3"

services:
  broker:
    image: redis:6.2.6
    ports:
      - 6379:6379

  database:
    image: mongo:4.4.5
    ports:
      - 27017:27017

  auth_database:
    image: postgres:14.2
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth
